### ISSUE TITLE
script命令错误

### ISSUE THREAD

**Issue by neove** [talentui/project-template#7]
开启构建分析的参数应该是`analysis=on` , 现在模版中是`analyzer_server=on`，导致不能开启相应的插件
![image](https://user-images.githubusercontent.com/18530075/42545709-2c379f74-84ec-11e8-8eaf-316b28b5e4d4.png)

**Comment by it1011** [comment]
fixed by commit [98c525e](https://github.com/talentui/project-template/commit/98c525e90ba83120a00829011ea23f8cfe4a1ff1)
